window.VEHICULOS_DATA = [
  {"id_vehiculo":1,"marca":"Tesla","modelo":"Model 3","precio_dia":85.0,"imagen_url":"tesla-model3.jpg","ciudad":"Madrid","plazas":5,"categoria":"electrico","disponible":1},
  {"id_vehiculo":2,"marca":"Seat","modelo":"Ibiza","precio_dia":35.0,"imagen_url":"seat-ibiza.jpg","ciudad":"Madrid","plazas":5,"categoria":"economico","disponible":1},
  {"id_vehiculo":3,"marca":"BMW","modelo":"Serie 1","precio_dia":60.0,"imagen_url":"bmw-serie1.jpg","ciudad":"Barcelona","plazas":5,"categoria":"compacto","disponible":1},
  {"id_vehiculo":4,"marca":"Audi","modelo":"A3","precio_dia":62.0,"imagen_url":"audi-a3.jpg","ciudad":"Valencia","plazas":5,"categoria":"compacto","disponible":1},
  {"id_vehiculo":5,"marca":"Mercedes","modelo":"Clase C","precio_dia":95.0,"imagen_url":"mercedes-clasec.jpg","ciudad":"Madrid","plazas":5,"categoria":"premium","disponible":1},
  {"id_vehiculo":6,"marca":"Volkswagen","modelo":"Golf","precio_dia":52.0,"imagen_url":"vw-golf.jpg","ciudad":"Sevilla","plazas":5,"categoria":"compacto","disponible":1},
  {"id_vehiculo":7,"marca":"Renault","modelo":"Clio","precio_dia":34.0,"imagen_url":"renault-clio.jpg","ciudad":"Malaga","plazas":5,"categoria":"economico","disponible":1},
  {"id_vehiculo":8,"marca":"Peugeot","modelo":"208","precio_dia":36.0,"imagen_url":"peugeot-208.jpg","ciudad":"Bilbao","plazas":5,"categoria":"economico","disponible":1},
  {"id_vehiculo":9,"marca":"Hyundai","modelo":"Tucson","precio_dia":68.0,"imagen_url":"hyundai-tucson.jpg","ciudad":"Madrid","plazas":5,"categoria":"suv","disponible":1},
  {"id_vehiculo":10,"marca":"Kia","modelo":"Sportage","precio_dia":66.0,"imagen_url":"kia-sportage.jpg","ciudad":"Barcelona","plazas":5,"categoria":"suv","disponible":1},
  {"id_vehiculo":11,"marca":"Toyota","modelo":"Corolla","precio_dia":48.0,"imagen_url":"toyota-corolla.jpg","ciudad":"Valencia","plazas":5,"categoria":"hibrido","disponible":1},
  {"id_vehiculo":12,"marca":"Nissan","modelo":"Qashqai","precio_dia":64.0,"imagen_url":"nissan-qashqai.jpg","ciudad":"Sevilla","plazas":5,"categoria":"suv","disponible":1},
  {"id_vehiculo":13,"marca":"Ford","modelo":"Focus","precio_dia":45.0,"imagen_url":"ford-focus.jpg","ciudad":"Madrid","plazas":5,"categoria":"compacto","disponible":1},
  {"id_vehiculo":14,"marca":"Opel","modelo":"Corsa","precio_dia":33.0,"imagen_url":"opel-corsa.jpg","ciudad":"Alicante","plazas":5,"categoria":"economico","disponible":1},
  {"id_vehiculo":15,"marca":"Citroen","modelo":"C3","precio_dia":32.0,"imagen_url":"citroen-c3.jpg","ciudad":"Zaragoza","plazas":5,"categoria":"economico","disponible":1},
  {"id_vehiculo":16,"marca":"Skoda","modelo":"Octavia","precio_dia":49.0,"imagen_url":"skoda-octavia.jpg","ciudad":"Murcia","plazas":5,"categoria":"familiar","disponible":1},
  {"id_vehiculo":17,"marca":"Volvo","modelo":"XC60","precio_dia":105.0,"imagen_url":"volvo-xc60.jpg","ciudad":"Madrid","plazas":5,"categoria":"premium","disponible":1},
  {"id_vehiculo":18,"marca":"Mazda","modelo":"CX-5","precio_dia":72.0,"imagen_url":"mazda-cx5.jpg","ciudad":"Barcelona","plazas":5,"categoria":"suv","disponible":1},
  {"id_vehiculo":19,"marca":"Fiat","modelo":"500","precio_dia":31.0,"imagen_url":"fiat-500.jpg","ciudad":"Valencia","plazas":4,"categoria":"urbano","disponible":1},
  {"id_vehiculo":20,"marca":"Mini","modelo":"Cooper","precio_dia":58.0,"imagen_url":"mini-cooper.jpg","ciudad":"Madrid","plazas":4,"categoria":"urbano","disponible":1},
  {"id_vehiculo":21,"marca":"Jeep","modelo":"Compass","precio_dia":74.0,"imagen_url":"jeep-compass.jpg","ciudad":"Sevilla","plazas":5,"categoria":"suv","disponible":1},
  {"id_vehiculo":22,"marca":"Honda","modelo":"Civic","precio_dia":50.0,"imagen_url":"honda-civic.jpg","ciudad":"Bilbao","plazas":5,"categoria":"compacto","disponible":1},
  {"id_vehiculo":23,"marca":"Lexus","modelo":"UX 250h","precio_dia":88.0,"imagen_url":"lexus-ux250h.jpg","ciudad":"Madrid","plazas":5,"categoria":"hibrido","disponible":1},
  {"id_vehiculo":24,"marca":"Cupra","modelo":"Formentor","precio_dia":78.0,"imagen_url":"cupra-formentor.jpg","ciudad":"Barcelona","plazas":5,"categoria":"deportivo","disponible":1},
  {"id_vehiculo":25,"marca":"Dacia","modelo":"Duster","precio_dia":55.0,"imagen_url":"dacia-duster.jpg","ciudad":"Valencia","plazas":5,"categoria":"suv","disponible":1},
  {"id_vehiculo":26,"marca":"Alfa Romeo","modelo":"Giulia","precio_dia":92.0,"imagen_url":"alfa-giulia.jpg","ciudad":"Madrid","plazas":5,"categoria":"premium","disponible":1},
  {"id_vehiculo":27,"marca":"Subaru","modelo":"Outback","precio_dia":81.0,"imagen_url":"subaru-outback.jpg","ciudad":"Pamplona","plazas":5,"categoria":"familiar","disponible":1},
  {"id_vehiculo":28,"marca":"Mitsubishi","modelo":"Eclipse Cross","precio_dia":67.0,"imagen_url":"mitsubishi-eclipsecross.jpg","ciudad":"Granada","plazas":5,"categoria":"suv","disponible":1},
  {"id_vehiculo":29,"marca":"Porsche","modelo":"Macan","precio_dia":140.0,"imagen_url":"porsche-macan.jpg","ciudad":"Marbella","plazas":5,"categoria":"premium","disponible":1},
  {"id_vehiculo":30,"marca":"Tesla","modelo":"Model Y","precio_dia":110.0,"imagen_url":"tesla-modely.jpg","ciudad":"Madrid","plazas":5,"categoria":"electrico","disponible":1},
  {"id_vehiculo":31,"marca":"MINI","modelo":"Electric Cooper SE","precio_dia":35.0,"imagen_url":"Mini-SE.jpg","ciudad":"Madrid","plazas":2,"categoria":"electrico","disponible":1},
  {"id_vehiculo":32,"marca":"Ford","modelo":"Expedition","precio_dia":65.0,"imagen_url":"Ford-Expedition.jpg","ciudad":"Madrid","plazas":7,"categoria":"suv","disponible":1},
  {"id_vehiculo":33,"marca":"BMW","modelo":"M3 Competition","precio_dia":120.0,"imagen_url":"BMW-Serie 3.jpg","ciudad":"Madrid","plazas":4,"categoria":"deportivo","disponible":1},
  {"id_vehiculo":34,"marca":"Ferrari","modelo":"488 GTB","precio_dia":150.0,"imagen_url":"Ferrari-488.jpg","ciudad":"Madrid","plazas":2,"categoria":"deportivo","disponible":1},
  {"id_vehiculo":35,"marca":"Porsche","modelo":"911 Carrera","precio_dia":140.0,"imagen_url":"Porsche-911.jpg","ciudad":"Madrid","plazas":2,"categoria":"deportivo","disponible":1}
]
;
